### PR TITLE
initialize component fields inline avoiding some initialization bugs

### LINKED ISSUE #155: Vue Components data initialization presents errors when entity has relations
Hi
I've been following this blueprint for a while and using it for an [aplication](https://github.com/ivangsa/ecolar/) so I would like to give a hand...

I found that generated 'constructor' for vue Components  has some errors initializing class fields when entity has relations

I belive these fields can be initialized 'inline' to null, {} or [] and still be reactive, so this code would be unnecessary and hard to maintain...

I have already a patch for this https://github.com/ivangsa/jhipster-vuejs/commit/2c58becf57302453bc2bac7f3309f3b18b8a4aaa, I will send a PR soon, after I launch all tests to verify it is all good..

Regards
ivan

### PR DESCRIPTION
**Pull request by ivangsa**
Fixes #155

### CODE REVIEW

**Comment by mraible** [comment]
It's great to see you here @ivangsa! For everyone that doesn't know Iván, he was [one of AppFuse's largest contributors](https://github.com/appfuse/appfuse/graphs/contributors). ❤️

**Comment by ivangsa** [comment]
It's nice to see you here as well Matt! Cheers!!

**Comment by ivangsa** [comment]
@sahbi-ktifa I pushed another commit to fix initialization of field 'reverse' order for entities, which is different for pagination and infinite-scroll, which I missed..

I'm still puzzled about those 3 tests that don't pass.. I've got them failing either way I initialize that class.. :-(

**Comment by sahbi-ktifa** [comment]
Everything seems good now right?

**Comment by ivangsa** [comment]
yes, test are passing now... it was a bit harder than anticipated..
(there is onw commit to be merged, just to let you know..)
cheers!

**Pull request merged**
