### PR TITLE
Fix redirect route path oauth2 to server

### LINKED ISSUE #371: Application not redirect path /oauth2 to server when using webpack
##### **Overview of the issue**

When I running the webpack server with command `yarn start` and I logged with Keycloak, the parameter redirect_uri with initial path with '/oauth2' is callled from keycloak to application, no route was found.

##### **Motivation for or Use Case**

When I start a webserver to local develop features, I want to login and redirect me to the application normally.

##### **Reproduce the error**

1) Start keycloak
2) Start registry
3) Start gateway
4) Start front-end webpack server
5) Try to login with Keycloak
6) Redirect to app fails

##### **Suggest a Fix**

Add the line '/oauth2' in the `webpack.dev.js`

```
devServer: {
    contentBase: './build/resources/main/static/',
    port: 9060,
    proxy: [
      {
        context: [
          /* jhipster-needle-add-entity-to-webpack - JHipster will add entity api paths here */
          '/api',
          '/management',
          '/swagger-resources',
          '/v2/api-docs',
          '/h2-console',
          '/login',
          '/auth',
          '/oauth2'
        ],
        target: 'http://127.0.0.1:8080',
        secure: false,
        headers: { host: 'localhost:9000' }
      }
    ],
```

##### **JHipster Version(s)**

6.0.1

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/viniciuscarvalho/Projects/sbt-platform/gateway
└─┬ generator-jhipster-vuejs@1.0.0
  └── generator-jhipster@6.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "br.com.sbt.gateway",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "br.com.sbt.gateway",
    "packageFolder": "br/com/sbt/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "testFrameworks": ["gatling", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.0.0"
      }
    ],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "pt-br",
    "languages": ["pt-br", "en"],
    "blueprint": "generator-jhipster-vuejs",
    "blueprintVersion": "1.0.0"
  },
  "generator-jhipster-vuejs": {
    "jhipsterVersion": "6.0.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "clientFramework": "vue",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm"
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.0

yarn: 1.15.2

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

MacOS Mojave 10.14.5
Versão 74.0.3729.169 (Version official) 64 bits

-   [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by vinicius91carvalho**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

Closes #371

### CODE REVIEW

**Comment by sahbi-ktifa** [comment]
Hi @vinicius91carvalho, thank you for this PR!
The CI failed, but that does not seem related to your addition. I'll investigate this and let you know!

**Comment by vinicius91carvalho** [comment]
@sahbi-ktifa Thanks very much!

**Comment by sahbi-ktifa** [comment]
@vinicius91carvalho Could you check that #378 works for you as well please ?

**Comment by vinicius91carvalho** [comment]
@sahbi-ktifa It works! I will reject this PR.

**Pull request closed without merging**
