### PR TITLE
Upgrade to generator-jhipster@6.10.0 and jhipster-core@7.3.4

### PR DESCRIPTION
**Pull request by pascalgrimaud**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/jhipster-vuejs/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
Did we introduce a typo by accident? `AssertionError: expected 'admin@localhost.jhpster' to equal 'admin@localhost.jhipster'`

**Comment by pascalgrimaud** [comment]
strange, I have no idea
I power off my computer so can't investigate right now

**Comment by atomfrede** [comment]
No problem. Will have try to help later today. Can't find the typo somewhere in the main generator

**Comment by pascalgrimaud** [comment]
I think it's random failures. Let me try to restart the CI

**Pull request merged**
