### PR TITLE
use i18n date time formatting for timestamps where possible

### LINKED ISSUE #177: Use vue-i18n date time localization
##### **Overview of the feature request**

Currently the display of date/time is hard coded (like in angular/react stuff).
As we only support evergreen browser we could use [Intl](http://www.ecma-international.org/ecma-402/2.0/#sec-intl-datetimeformat-constructor) date time formatting and use the build in filters
for format dates: https://kazupon.github.io/vue-i18n/guide/datetime.html

##### **Motivation for or Use Case**

Better user experience

##### **Related issues or PR**

* https://github.com/jhipster/jhipster-vuejs/pull/144
* https://github.com/jhipster/jhipster-vuejs/issues/94

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by atomfrede**
closes #177

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
:thinking: Something went wrong during rebase :-1: Will have a look and fix it.

**Comment by pascalgrimaud** [comment]
@atomfrede : FYI, @nonomoho is working on fixing the current build. We encountered some issue related to date / instant etc...
It looks like this PR is for another thing, but I wanted to let you know

**Comment by atomfrede** [comment]
This PR is ready to merge now. All dates are now formatted via [vue-i18n](https://kazupon.github.io/vue-i18n/guide/datetime.html) which uses the native [Intl Api](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl). Right now the date is parsed on demand. When doing https://github.com/jhipster/jhipster-vuejs/issues/482 it must not be done (will be a separate PR).

**Comment by atomfrede** [comment]
Thats how it looks like (before we had the same pattern in every language)

Screenshot_2019-12-02 datei18n(3)
Screenshot_2019-12-02 datei18n(2)
Screenshot_2019-12-02 datei18n(1)
Screenshot_2019-12-02 datei18n

**Comment by clement26695** [comment]
It looks very cool @atomfrede !

**Comment by atomfrede** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/12029

**Pull request merged**
