### PR TITLE
Clean npm test logs output

### PR DESCRIPTION
**Pull request by nonomoho**
Related to #220 

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@nonomoho : are you working on this ? I'd like to do a few fix directly in your branch, then we can merge this.

**Comment by nonomoho** [comment]
Not for the moment, I'll try to do this next week with @hdurix. 
But if you want, you can do some fix directly on my branch yes.

**Comment by pascalgrimaud** [comment]
Thanks @nonomoho and good job for this PR.
Some minor fix and everything works fine!

**Comment by sahbi-ktifa** [comment]
Yes, very good job @nonomoho !
However, I'd like you do not update package-lock.json here. It would be perfect if you could remove it from this PR.

**Comment by pascalgrimaud** [comment]
ahhhhhhhhhhhhhhhhhhh ! don't understand why there are 4 Travis builds !

**Comment by pascalgrimaud** [comment]
There are still some other warnings in npm test logs output.
I'll do another PRs to try to fix them all

**Comment by pascalgrimaud** [comment]
For the relation with User entity, it seems good, as it is tested in our CICD ! :)

**Pull request merged**
