### PR TITLE
Provide a new cli command

### PR DESCRIPTION
**Pull request by nonomoho**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by nonomoho** [comment]
@sahbi-ktifa
I push my first try to add a custom CLI command. I think all npm links are goods when I try to use it.
Can you take a look on it?

**Comment by sahbi-ktifa** [comment]
Hi @nonomoho, everything seems to be good to me! Keep going!

**Comment by nonomoho** [comment]
Yes but I still have the same error when I try `jhipster --blueprint vuejs foo`:
``` bash
INFO! No custom command found within blueprint: generator-jhipster-vuejs
INFO! Using JHipster version installed globally
ERROR! foo is not a known command. See 'jhipster --help'.
```

**Comment by sahbi-ktifa** [comment]
Oh, that is related to npm links issues I guess. You have to use npm link on both blueprint and main generator while this is not released

**Comment by nonomoho** [comment]
Yes I use npm link on both blueprint. I try it with @hdurix and we doesn't understand what is wrong :disappointed:

**Comment by avdev4j** [comment]
Hi @nonomoho 
I'm facing with the same issue on a blueprint and a generator (cd-myBlueprint).

There is how I can launch it on my own context:

```
npm i /Users/aviard/projects/jhipster-myBlueprint/generator-jhipster-myBlueprint
npm link generator-jhipster
jhipster cd-myBlueprint --blueprints c4
```

my commands.js :
```
module.exports = {
    'cd-myBlueprint': {
        desc: 'myBlueprint CD generator',
        blueprint: 'generator-jhipster-myBlueprint'
    }
};
```
Sometimes I can't figure out how npm works :s

**Comment by nonomoho** [comment]
Hi @avdev4j 

I made some tests last week with @pascalgrimaud: 
To make it works you need to run `npm link your-blueprint` and `npm link generator-jhipster`  in the directory where you want to create an application. I think it's not a good idea because you will have some conflicts between the generator you linked and the one imported with your blueprint.

I think we need to improve the loading of blueprint's commands and maybe rework https://github.com/jhipster/generator-jhipster/pull/9574.

**Pull request closed without merging**
