### PR TITLE
Fix delete confirmation dialog i18n(#501)

### LINKED ISSUE #501: Delete alert confirmation is not correctly internationalized
Delete alert confirmation is not correctly internationalized inside generated entity list vue components. Default value shown but i18n file has another value

### PR DESCRIPTION
**Pull request by weblogichub**
Fixes #501

### CODE REVIEW

**Comment by atomfrede** [comment]
thanks @weblogichub Don't worry about the failed build it is because we have not yet updated to latest main generator version.

**Comment by pascalgrimaud** [comment]
close / reopen for restarting the build

**Comment by hdurix** [comment]
I just tested your change, the translation is now correctly handled but e2e tests are failing: the `Delete` button doesn't open the delete modal in the first time, you need to click twice on the button.
I've found the fix: by adding:
```ts
    if (<any>this.$refs.removeEntity) {
      (<any>this.$refs.removeEntity).show();
    }
``` 
at the end of the method [prepareRemove](https://github.com/jhipster/jhipster-vuejs/blob/master/generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.component.ts.ejs#L93) as @atomfrede [did](https://github.com/jhipster/jhipster-vuejs/pull/459/files) for [user management](https://github.com/jhipster/jhipster-vuejs/blob/master/generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs#L100-L105).

You can give it a try on this branch.

**Comment by pascalgrimaud** [comment]
Closing this PR in favor of https://github.com/jhipster/jhipster-vuejs/pull/542

**Pull request closed without merging**
