### PR TITLE
use login regex from main generator

### PR DESCRIPTION
**Pull request by atomfrede**
updates #605

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/jhipster-vuejs/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
Need to to some manual testing, so wait a few moments before merging

**Comment by atomfrede** [comment]
There is strange difference in the generation between angular/main and vue.js (but we can live with that for now imho):

* angular: `^[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\\\\.[a-zA-Z0-9-]+)*$|^[_.@A-Za-z0-9-]+$` --> `^[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$|^[_.@A-Za-z0-9-]+$` (see the `\.`)
* vue: `^[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\\\\.[a-zA-Z0-9-]+)*$|^[_.@A-Za-z0-9-]+$` -> `^[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$|^[_.@A-Za-z0-9-]+$` (see the `\\.` which is not correct imho)

**Comment by pascalgrimaud** [comment]
it's really so complex lol

**Comment by pascalgrimaud** [comment]
Feel free to merge it @atomfrede as soon as you think it's OK

**Pull request merged**
