### PR TITLE
Fix Websocket support

### LINKED ISSUE #116: Websocket support broken
The support for Websocket is currently broken in master, with the error:

```
Error: ERROR! Copying template vue/src/main/webapp/app/components/admin/tracker/trackerService.vue.ejs failed. [Error: ENOENT: no such file or directory, open '/home/pgrimaud/projects/jhipster/jhipster-vuejs/generators/client/templates/vue/src/main/webapp/app/components/admin/tracker/trackerService.vue.ejs']
    at Environment.error (/home/pgrimaud/projects/jhipster/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/home/pgrimaud/projects/jhipster/jhipster-vuejs/node_modules/generator-jhipster/generators/generator-base.js:2444:18)
    at ejs.renderFile (/home/pgrimaud/projects/jhipster/jhipster-vuejs/node_modules/generator-jhipster/generators/utils.js:206:23)
    at tryHandleCache (/home/pgrimaud/projects/jhipster/jhipster-vuejs/node_modules/ejs/lib/ejs.js:254:14)
    at Object.exports.renderFile (/home/pgrimaud/projects/jhipster/jhipster-vuejs/node_modules/ejs/lib/ejs.js:482:10)
    at Object.renderContent (/home/pgrimaud/projects/jhipster/jhipster-vuejs/node_modules/generator-jhipster/generators/utils.js:202:9)
    at module.exports.template (/home/pgrimaud/projects/jhipster/jhipster-vuejs/node_modules/generator-jhipster/generators/generator-base-private.js:667:23)
    at blockTemplate.templates.forEach.templateObj (/home/pgrimaud/projects/jhipster/jhipster-vuejs/node_modules/generator-jhipster/generators/generator-base.js:2831:42)
    at Array.forEach (<anonymous>)
    at module.exports.writeFilesToDisk (/home/pgrimaud/projects/jhipster/jhipster-vuejs/node_modules/generator-jhipster/generators/generator-base.js:2793:45)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/pgrimaud/projects/jhipster/jhipster-vuejs/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:427:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Following this PR https://github.com/jhipster/jhipster-vuejs/pull/115, the fix would be:
- use an inject service for tracker
- add npm test
- add Travis tests

### PR DESCRIPTION
**Pull request by hdurix**
Fix #116

### CODE REVIEW

**Comment by hdurix** [comment]
Compilation is ok now but websocket is still not working yet.

**Comment by pascalgrimaud** [comment]
You need to rebase, as @sahbi-ktifa did a big refactoring

**Comment by pascalgrimaud** [comment]
@hdurix : don't hesitate to ping me when it's done, so I can test and merge your PR

**Comment by hdurix** [comment]
Yes I'm still working on it but it should be good in few minutes :)

**Comment by pascalgrimaud** [comment]
So it's ready, I'll do the review soon

**Comment by pascalgrimaud** [comment]
Just did the test.
A very minor issue: when the user logout, he is still in the list. I don't know if it's normal or not.
But for all other tests I did, looks good to me !

**Pull request merged**
