### PR TITLE
Vue-CLI compatibility

### LINKED ISSUE #6: Cleanup and align with decided architecture
Make sure the following are followed, update and align where necessary

- [x] VueJS completely in Typescript
- ~~Tsx for templates~~
- [x] Bootstrap vue
- [x] Vuex for state management
- [x] Vue Router
- [x] Vue CLI as much as possible
- [x] Axios for HTTP
- [x] Vuei18n if it can be used without rewritting current i18n files, else use a transformation step or write our own i18n adapter like in React
- [x] Sass only
- [x] Jest for unit tests
- [x] Protractor if it works without any additional work else we can switch to Cypress
- [x] Tslint , prettier

### PR DESCRIPTION
**Pull request by sahbi-ktifa**
Updates and closes #6 
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by sahbi-ktifa** [comment]
I've got trouble to run default vue-cli tasks (build / serve) as it uses internal webpack configurations. i'm trying to override these but no luck at the moment.

**Comment by atomfrede** [comment]
:+1: Thats sound already great. Having jhipster apps in the vue cli ui will be a huge thing I guess (and to show at talks)

**Comment by sahbi-ktifa** [comment]
After further investigations, vue-cli webpack configurations is not as tweakable as we thought. Besides, as our tasks do the job properly, vue-cli private tasks (build/serve) do not bring anything special.

**Comment by deepu105** [comment]
I wanted to take a look at current state as well, haven't found time yet.
Will try over the weekend. Also we need to create a lib similar to
ng-jhipster and react-jhipster to hold reusable front end code to reduce
the amount of code generated

**Comment by atomfrede** [comment]
@deepu105 Let's wait with a vue lib until the blueprint has stabilized a little. Having another dependency makes it hard to try things out easily and fast imho

**Pull request merged**
