### PR TITLE
Load required only bootstrap components

### PR DESCRIPTION
**Pull request by sahbi-ktifa**
Using this, I managed to lower bundle size about 30KB

capture d ecran 2018-12-20 a 18 41 05

Updates #129.

### CODE REVIEW

**Comment by atomfrede** [comment]
@sahbi-ktifa Can you resolve the conflicts? Would like to integrate that into my date-fns branch and see whats breaking on my branch

**Comment by sahbi-ktifa** [comment]
@atomfrede yes sir, conflicts resolved :)

**Comment by atomfrede** [comment]
Great! Lets merge this and afterwards the moment removal as the build is now green. We should just make sure somehow everybody is aware one must use the latest main generator master branch to have the entity fields for dates customizable

**Comment by sahbi-ktifa** [comment]
We may force that by updating package-lock.json I guess.

**Pull request merged**
