### PR TITLE
Added no sql db tests

### LINKED ISSUE #435: Add MongoDB and Cassandra in travis/azure test automation
##### **Overview of the feature request**

Add travis/azure tests for `'cassandra', 'mongodb', 'couchbase'`
##### **Motivation for or Use Case**

I am doing a PR at https://github.com/jhipster/jhipster-vuejs/pull/434 and hence would like to have validated against all DBs types.

Was there any issue for these DBs or simply not added yet?
If it is the latter case, I can do a PR.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by pmverma**
Fixes #435 

This is a copy/paste from the main generator with little modification for vuejs.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pmverma** [comment]
This is `ready-to-merge-when-ci-pass` 😄

**Comment by pmverma** [comment]
@pascalgrimaud @sahbi-ktifa Can you please restart the Azure builds?

**Comment by pascalgrimaud** [comment]
it will fail, because we use generator-jhipster from master and a new version was released yesterday.
We need to upgrade the version in package.json from 6.1.2 to 6.2.0

**Comment by pmverma** [comment]
@pascalgrimaud I am testing locally for mongo-kafka-vue for e2e. It is strange that e2e tests are failing for admin screen.

**Comment by pmverma** [comment]
I traced the current issue. It is because of the inconsistent prefix value.

The actual links for menu items are like followings:

```
/admin/my-prefix-metrics
/admin/my-prefix-health
/admin/my-prefix-configuration
```

But in the tests, the parameter to click the links are `jhi-metrics, jhi-health, jhi-configuration` rather than `my-prefix-metrics, my-prefix-health, my-prefix-configuration`.

I am wondering why only these three menu items are prefixed. It should be prefixed in all links or none.

I will check and do a PR for it.

**Comment by pmverma** [comment]
This PR is ready to merge.

**Comment by pascalgrimaud** [comment]
thanks a lot @pmverma

**Pull request merged**
