### PR TITLE
Add tests for session authentication & fix TypeScript compilation

### LINKED ISSUE #110: Add Travis sample for session based authentication
If I'm right, Travis does not test any project with authentication mechanism other than JWT.

I just noticed than the option "session" does not compile (since the use of TypeScript I think): I will look at it.

### PR DESCRIPTION
**Pull request by hdurix**
Fix #110

### CODE REVIEW

**Comment by hdurix** [comment]
Yes good idea!

**Comment by hdurix** [comment]
@pascalgrimaud is that ok for you?

**Comment by pascalgrimaud** [comment]
yes LGTM

**Comment by sahbi-ktifa** [comment]
Hum... Shouldn't you change the travis sample filename to vuejs-gradle-session ?

**Pull request merged**
