### PR TITLE
Upgrade to generator-jhipster 6.3.1

### PR DESCRIPTION
**Pull request by pascalgrimaud**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
Looks like we have to adapt the e2e tests, It doesn't look like a hiccup as basically all are failing for each variant

**Comment by pascalgrimaud** [comment]
sad if the e2e tests failed again...

**Comment by vishal423** [comment]
Is there a real issue as I see `MapsIdUserProfileWithDTO e2e test` fails consistently on few jobs?

**Comment by vishal423** [comment]
or if these are due to slow api response or other animations, then, we can try to increase wait from `10s` to `30s`

**Comment by atomfrede** [comment]
I will check later if they fail locally.

**Comment by atomfrede** [comment]
I could not make e2e fail on my local machine using latest main generator master and blueprint

**Comment by pascalgrimaud** [comment]
Closing in favor of https://github.com/jhipster/jhipster-vuejs/pull/471

**Comment by pascalgrimaud** [comment]
For your information, there is no flaky e2e tests here, only real bugs, related to:
- something related MapsId
- new readonly feature
- broken couchbase +  jdk8
- Travis builds not up-to-date (as jdk8 has been removed by default)

So no worry @vishal423, your work was good, thanks so much.
I will do my best to fix all these items tomorrow and do a new release of this blueprint.
It's my priority !

**Pull request closed without merging**
