### PR TITLE
Fix e2e tests

### LINKED ISSUE #285: Protractor tests: random failures
Our protractor tests still failed randomly.

See:
- https://travis-ci.com/jhipster/jhipster-vuejs/jobs/175764686
- logs:
```
  Account
    ✓ should fail to login with bad password
    1) should login with admin account
    2) should be able to sign up
    3) should load user management
```

As it is always at the same tests, I suspect there is something to do here.

### PR DESCRIPTION
**Pull request by vishal423**
closes #285

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vishal423** [comment]
Finally, the azure build pipeline completed with a relieving green indicator. Now, keeping an eye on the Travis God.

**Comment by vishal423** [comment]
@pascalgrimaud, both Travis and Azure builds seems to be good :smile:

**Comment by pascalgrimaud** [comment]
@vishal423 : wow, are you confident ? can we merge this ?

**Comment by hdurix** [comment]
I notice some errors in the e2e test logs, see for instance https://dev.azure.com/jhipster/jhipster-vuejs/_build/results?buildId=3956&view=logs&jobId=1e6893c2-de64-5b3c-8827-c4b670bc86e5&taskId=0ab4855e-99aa-5075-f9cc-d5e26253abba&lineStart=324&lineEnd=346&colStart=1&colEnd=35

Are we sure tests are passing for good?

**Comment by vishal423** [comment]
@hdurix , If you are referring to below logs, then, those are on purpose and can be controlled. If an element is not visible within a 30s timeframe, then, we log the below message and the test case continue process / assert remaining statements (an important thing to note is that we don't skip any test or an element interaction). It was required as I couldn't find an elegant way to ensure the completion of GET ALL APIs request (to differentiate between no records and pending response scenario). 

This is much simpler in angular as the framework itself wait for the underlying promises to complete. On the react side, we took a different approach to always create 2 records with the same data (in a create entity test https://github.com/jhipster/generator-jhipster/pull/9265) to avoid no records scenario. Though that solution partially works, I personally don't like that as it creates two database records with the same dataset in a test case which was supposed to create only one and it would further fail if you have a unique constraint on some attributes.

I can see few limitations of my current approach:
- If no records exist in the database, then, it adds a delay of 30s per entity test scenario. It's clearly visible in the time taken by tests to execute on travis/azure build pipelines. In my opinion, stability is more important, so, we can live with it.

A more appropriate solution would be to have some indicators on UI like loading spinner to convey that an operation is in progress and e2e tests can wait for that spinner to go away. I don't have any immediate plan to look/use vue.js, so, if anyone is willing to add/support this, then, we can gradually update the e2e code/assertions.

> 
> { TimeoutError: "By(css selector, div table .btn-danger)" not found in the Page Object class ''
> Wait timed out after 30006ms
>     at /home/vsts/app/node_modules/selenium-webdriver/lib/promise.js:2201:17
'' }

@pascalgrimaud , from my side, it's done and can be merged.

**Comment by hdurix** [comment]
@vishal423, thanks for the explanation! That can be a first solution even if it takes more time. Maybe once it's stable, we could decrease the 30s timeout to a lower value.

Could you just check for the failing test `Account should login with admin account` before merging? https://dev.azure.com/jhipster/jhipster-vuejs/_build/results?buildId=3956&view=logs&jobId=902a2790-24a1-55bd-8880-12969d01f8eb&taskId=41d5cfb2-e5e5-5814-2144-ddb76ab4aee0&lineStart=353&lineEnd=354&colStart=1&colEnd=1

**Comment by vishal423** [comment]
@hdurix, that test case seems to fail as login dialog was still visible after a wait of 30s. Could that be due to some login issue?

Anyway, I propose to merge this and monitor future builds to identify intermittent failures. Those failures can be consolidated and analyzed to take further action.

**Comment by hdurix** [comment]
Since the last build is green, I agree that we can merge it. @pascalgrimaud are you ok?

**Comment by pascalgrimaud** [comment]
yes very good job @vishal423 !

**Comment by hdurix** [comment]
Yes thanks a lot!!!

**Comment by vishal423** [comment]
#362 can help in reducing 30s wait. I have left one comment about a scenario that should be properly handled.

**Pull request merged**
