### PR TITLE
Fix sorting entities, audits & users

### LINKED ISSUE #405: Sort a column in an entity is not calling the backend
##### **Overview of the issue**

For jhipster apps using angular, sorting an entity is doing on server side (https://\<domain>/api/\<entity>?page=0&size=20&sort=\<field>,asc&sort=id)

For jhipster apps using vuejs blueprint this behaviour is only done on the front. So the sort is only relevant for the current page.

##### **Motivation for or Use Case**

Sort should be processed on the whole entity and not only on the current page

##### **Reproduce the error**

Click on the sort button on an entity (you can open the Chrome Console. No call to the backend is sent)

##### **Related issues**

#29 

##### **Suggest a Fix**

I'm not an expert on vuejs but I will  try to check this if I have some times

##### **JHipster Version(s)**

Same config as #404 

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by clement26695**
Fix #405 

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vishal423** [comment]
aah... I have conflicting changes on my PR #423 to comply with current sort behavior (ascending / descending based on pagination support)

**Comment by clement26695** [comment]
So I have to rebase and modify the tests?

**Comment by fleboulch** [comment]
Thanks @clement26695!
I didn't find time to work on it

**Comment by vishal423** [comment]
If your change doesn't alter the sort order behavior, then, I think it should be fine.

**Comment by clement26695** [comment]
I just rebased and tests are still green :+1:

**Pull request merged**
