### PR TITLE
feature: add no database support

### LINKED ISSUE #412: "No database" option from generator-jhipster is not supported
##### **Overview of the issue**

The "no database" option from the generator jhipster is not supported.

##### **Motivation for or Use Case**

Be coherent with generator-jhipster

##### **Reproduce the error**

Create an app with no database and no translation

##### **JHipster configuration**

App generated with master from both generator-jhipster and generator-jhipster-vuejs

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by clement26695**
Fix #412 

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by sahbi-ktifa** [comment]
@clement26695  Is it a CI random failure ?

**Comment by clement26695** [comment]
I think so, yes. I'll try to restart the CI

**Comment by vishal423** [comment]
@clement26695, can you also rebase against master?

**Comment by clement26695** [comment]
CI is green!

**Comment by hdurix** [comment]
Thanks @clement26695!

**Pull request merged**
