### PR TITLE
Update yeoman dependencies

### PR DESCRIPTION
**Pull request by pvliss**
Similar to https://github.com/jhipster/generator-jhipster/pull/9267 this PR updates the yeoman dependencies as follows:
- `yeoman-generator: 3.2.0`
- `yeoman-environment: 2.3.4`
- `yeoman-test: 1.9.1`

I have tested these for the main generator and the Kotlin and VueJS blueprints for https://github.com/jhipster/generator-jhipster/pull/9266

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Thanks @pvliss
I put on hold label, as I need to check if it is compatible with generator-jhipster 5.8.1, master or both.

It is because we plan to do a release next week and I don't want something broken because of different dependencies between this blueprint and generator-jhipster

**Comment by pvliss** [comment]
@pascalgrimaud  Yes, I understand. By release you mean final? If so I did not realize and I was under the impression you were building against current master(6.x) but I did not check. I can change it if you want to match the ones in v5.8.1(which seem to be the same with 5.x maintenance as well). BTW, is there a plan to release a 5.8.2 as well? I could do a PR to update the dependencies over there as well and see if `npm test` and CI builds pass which I guess is enough? The biggest change I see is moving from `yeoman-generator` 2.0.5 to 3.x.x and JHipster 5.8.1 is already at 3.0.0, so that should not be a big problem.

**Comment by pvliss** [comment]
Forgot to mention that running `npm install` generates a lot of security warnings mainly related to `lodash` and there are 2-3 more dependencies that could be updated as well. Again if you are targeting 5.8.1 I guess these can wait but should be checked nonetheless

**Comment by pascalgrimaud** [comment]
> The biggest change I see is moving from yeoman-generator 2.0.5 to 3.x.x and JHipster 5.8.1 is already at 3.0.0

in that case, let's merge this !!!

**Comment by pvliss** [comment]
Wow, that was fast!!!

**Comment by pvliss** [comment]
Thanks @pascalgrimaud

**Comment by pvliss** [comment]
Would you like me to check the other dependencies as well by using `npm audit fix` or will you take care of it instead?

**Comment by pascalgrimaud** [comment]
No computer this weekend for me (only my phone), so if you have the bandwidth, yes, it will help us a lot.

**Comment by pvliss** [comment]
Oh, OK. Yes, I will check and create PRs as needed. Thanks

**Comment by pascalgrimaud** [comment]
You contribute a lot, to the organization JHipster, the last weeks / months.
Maybe you would be interested to join us ?

**Comment by pvliss** [comment]
@pascalgrimaud Sure, I would be honored!!!

**Comment by pascalgrimaud** [comment]
Give me few days and I'll speak to Julien :-)

**Comment by pvliss** [comment]
Thanks @pascalgrimaud. I really appreciate this

**Pull request merged**
