### PR TITLE
fix pagination with filtering

### LINKED ISSUE #379: Pagination problem when filtering
##### **Overview of the issue**

Same as jhipster/generator-jhipster#9808.

##### **Reproduce the error**

Take a look at :
https://github.com/clement26695/9808-vue

##### **Related issues**

jhipster/generator-jhipster#9808.

##### **Suggest a Fix**

change v-if condition to a v-hidden in the entity component

##### **JHipster Version(s)**
6.0.1

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by clement26695**
Fix #379 

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by sahbi-ktifa** [comment]
Tests are failling, just adapt them I think, it should be enough! 
Well done otherwise :)

**Comment by hdurix** [comment]
@clement26695 could you please rebase now #393 is merged: CI tests should be green now :)

**Comment by sahbi-ktifa** [comment]
@clement26695 is it still worthy ?

**Comment by clement26695** [comment]
Some frontend test is failing. I will investigate further to see what is wrong

**Comment by clement26695** [comment]
I think the test is failing because of #406. I will rebase once #421 is merged.

**Pull request merged**
