### PR TITLE
Admin pages + specs

### LINKED ISSUE #30: Add administration pages
Add all administration pages (audits, metrics, ...)

### PR DESCRIPTION
**Pull request by sahbi-ktifa**
Add admin pages to application
Create separate ts component + specs.

Fixes #30

### CODE REVIEW

**Comment by sahbi-ktifa** [comment]
Please someone could review this one, as it's blocking e2e tests work in progress, entity pagination, etc.

I've almost finished protractor tests but I'm working on this branch right now, I would feel more comfortable if this is merged.

**Comment by deepu105** [comment]
Overall looks ok to me. I don't have time for detailed review now. If you are confident merge it as we are in WIP anyway

**Comment by pascalgrimaud** [comment]
Same comment than Deepu.
Don't hesitate to merge directly @sahbi-ktifa

**Comment by sahbi-ktifa** [comment]
Great! Thanks guys, let's move on!

**Pull request merged**
