### PR TITLE
Travis: improvements with prod profile

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Fix https://github.com/jhipster/jhipster-vuejs/issues/269

- prod profile
- sass to true by default
- default protractor tests for all config

_____

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I rebased my work few days ago, and still have failed builds.

**Comment by sahbi-ktifa** [comment]
The theme build fails because of the capitalized title brought by the theme. In #335, I changed it to focus on the content being here not what it really is. If this is the last build not passing, I suggest we wait for the other one to be merged and then, go :)

**Comment by sahbi-ktifa** [comment]
Could you rebase again your branch please @pascalgrimaud ?
I will investigate on the gradle/session protractor tests that fail ASAP.

**Comment by pascalgrimaud** [comment]
I'm doing this! you're so fast :D

**Comment by sahbi-ktifa** [comment]
I pushed a fix to your branch, we can wait for the CI now

**Pull request merged**
