### PR TITLE
Add uaa support

### PR DESCRIPTION
**Pull request by Brouilles**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/jhipster-vuejs/actions) are green
-   [ ] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
wahou ! thanks a lot @Brouilles !!

I don't have time to review it right now, as I'm on my day job time :)

But I have few comments, plz can you:
- add npm test for UAA application, see https://github.com/jhipster/jhipster-vuejs/blob/master/test/generator.spec.js
- add CI with UAA
    - see https://github.com/jhipster/jhipster-vuejs/blob/master/test/generator.spec.js
    - and https://github.com/jhipster/jhipster-vuejs/tree/master/test-integration/samples-vuejs

**Comment by Brouilles** [comment]
No problem & thanks for your answer.
J'ai regardé le fichier de test. I have just to do the same like JWT but with UAA for `authenticationType` and gateway for `applicationType`? Or I need to setup a configuration to start an UAA server during test?

Thanks.

**Comment by pascalgrimaud** [comment]
> I have just to do the same like JWT but with UAA for authenticationType and gateway for applicationType?

Exactly.
About the CI, how it works:
- merge of these folders:
    - https://github.com/jhipster/jhipster-vuejs/blob/master/test-integration/scripts/10-install-jhipster-vuejs.sh#L85
        - https://github.com/jhipster/jhipster-vuejs/tree/master/test-integration/samples-vuejs
        - https://github.com/jhipster/generator-jhipster/tree/master/test-integration/samples
    - so it will contain UAA app -> https://github.com/jhipster/generator-jhipster/tree/master/test-integration/samples/uaa
- at the generation, if your app name contains `uaa`, it will generate the server
    - https://github.com/jhipster/jhipster-vuejs/blob/master/test-integration/scripts/12-generate-project-vuejs.sh#L17-L23
    - so it is important to name the folder `ms-vuejs-gateway-eureka-uaa` for example
- before running the app, it will check if the name contains uaa, so it will start the uaa server
    - https://github.com/jhipster/generator-jhipster/blob/master/test-integration/scripts/24-tests-e2e.sh#L71-L81

**Comment by ruddell** [comment]
I did not test manually but have some notes below.

References to `services/uaa` should be replaced with `<%- apiUaaPath %>` which is [configured here](https://github.com/jhipster/generator-jhipster/blob/a4c8339ad2cfcb6aa49f6f2bc92d69edf34f5e1b/generators/client/index.js#L345), users can configure a UAA name other than `uaa`.  That should also let you use the same code for most endpoints, because it is set to an empty string when UAA is not selected.

Logout endpoint needs to be handled (code in [main generator](https://github.com/jhipster/generator-jhipster/blob/07b209955cf30a29ab2608e225cac605c91f844d/generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs#L48-L58)), as well as the audits endpoint (code in [main generator](https://github.com/jhipster/generator-jhipster/blob/07b209955cf30a29ab2608e225cac605c91f844d/generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.service.ts.ejs#L39)).

**Comment by Brouilles** [comment]
Hi, 
You have right @ruddell. I have commit the changes.
Thanks.

**Comment by Brouilles** [comment]
Thanks for your answer @pascalgrimaud ! Like you (I think) it's complicated because I'm homebound because of the Coronavirus in France. So the time to get organized, I don't know when I will be able to set up the tests.

**Comment by pascalgrimaud** [comment]
Yes, same situation like you... 

No worry, I can help if you want.
I'll try to find time to put what is missing in this PR so :)

**Comment by pascalgrimaud** [comment]
First of all, thanks for trying to add the support for UAA.
I did a quick review this morning, and it's not ready.

The tests I did:
- I generate a UAA server
- I generated a UAA+Eureka Gateway 
- I can't start my gateway app, as there are a lot of error

I had a quick look on your code, and nothing is done for managing UAA files:
- https://github.com/jhipster/jhipster-vuejs/blob/master/generators/client/files.js

That's why tests are important.
Something similar to https://github.com/jhipster/generator-jhipster/blob/master/test/app.spec.js#L1837-L1877 will help.

**Comment by Brouilles** [comment]
I can't do more. It's working for me with the current release branch and adding this modifications directly in the project. I have don't try with the automatic system than generate the project. I have do it just for help. 

I have no time for creating test and debug for specifically for `jhipster-vuejs`. Sorry. 
But on my side, with the generation of a project with the deploy release version of jhipster-vuejs and just editing the code with my first commit (without the `<%- apiUaaPath %>`, I don't try with it) it's working very good.

Have a good day.

**Comment by pascalgrimaud** [comment]
No worry @Brouilles it's already nice to try to add UAA support, so for that thank you very much. And don't be sorry plz :)

Then, honestly on my side, I don't care about UAA, as I don't use for my projects, so I don't spend time to support something I don't use.
And in main generator, the support is not really good.. too flaky tests, and no one want to contribute as it requires too much effort as you can see.

So let's close this PR.
Have a good day. And again, don't be sorry ;)

**Pull request closed without merging**
