### PR TITLE
Metrics page with Micrometer

### LINKED ISSUE #200: Metrics page with Micrometer
With the hard work by @clement26695, Micrometer is now official in generator-jhipster, after some merges:
- https://github.com/jhipster/generator-jhipster/pull/8812
- https://github.com/jhipster/jhipster/pull/123
- https://github.com/jhipster/ng-jhipster/pull/81
- https://github.com/jhipster/react-jhipster/pull/20

So, the metrics page for Vue.js need to be updated.

### PR DESCRIPTION
**Pull request by clement26695**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

Should close #200

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
are you serious @clement26695 ? Already done ?!
You're awesome !!

**Comment by sahbi-ktifa** [comment]
Truly amazing ! :clap: :clap:

**Comment by jdubois** [comment]
Yes @clement26695 is alone at Ippon today, congrats for your great work!!

**Comment by sahbi-ktifa** [comment]
Congrats on your first contribution here @clement26695 :raised_hands: :muscle:

**Pull request merged**
