### PR TITLE
Add Cypress support for e2e testing

### PR DESCRIPTION
**Pull request by clementdessoude**
As we had some issues with Protractor (which should hopefully be resolved thanks to @vishal423 !), I started to look at a Cypress integration with JHipster. Let me know if you think it could be a good improvement.

I managed to arrive in a good state, but some improvements need to be done to follow the best practices of Cypress. Anyway, I'm open to suggestions :smile: !

If you want to look at the result in the ci, you can check https://dev.azure.com/clementdessoude/Test/_build?definitionId=10, and filter on the add-cypress branch. In the last 10 builds, only one fails due to one test.

PS: I have to squash :) 

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vishal423** [comment]
Only problem I have with cypress is their cross browser support and that doesn't seems priority for them

**Comment by deepu105** [comment]
I have used cypress in our company. While I liked many of its features. I have few issues though.

1. I'm not in favor of providing 2 options for e2e
2. The last I checked cypress cant run tests in parallel and it's very slow overall compared to Protractor(Maybe things changed now). It becomes really slow if you have a lot of e2e tests
3. Though it promises not to be flaky, I have experienced otherwise(so this really depends on the tests and not a framework)

I suggest you open a ticket to discuss first. Also, we should try to be in sync between different frontends

**Comment by tillias** [comment]
Is there any example how to use cypress with JWT? It seems localStorage is not used but sessionStorage instead for jhi generated projects?

**Comment by pascalgrimaud** [comment]
@tillias : have a look at main generator-jhipster project. It's already implemented there, and it will be available for v7 :)

**Comment by tillias** [comment]
idk, I have tested it with code from diff (this ticket):

```
describe('test', () => {
    it('check login works programmatically', () => {

        cy.request({
            method: 'POST',
            url: '/api/authenticate',
            body: {
                username: 'admin',
                password: 'admin',
                rememberMe: null
            }
        }).then((result: any) => {
            const bearerToken = result.headers.authorization;
            if (bearerToken && bearerToken.slice(0, 7) === 'Bearer ') {
                window.sessionStorage.setItem('jhi-authenticationToken', bearerToken.slice(7, bearerToken.length));
            }
        }).then(() => {
            cy.visit('/admin');
            cy.get('.lead').should('have.text', 'Here is microservices catalog');
            cy.get('#home-logged-message').should('have.text', 'You are logged in as user "user".');
        });
    })
})
```

and it still fails. Have you tested it with chrome, firefox or ie? Which browser is needed?

**Comment by pascalgrimaud** [comment]
@tillias :
- don't use this pull request, it's so old...
- I generated a JHipster project with main branch: https://github.com/pascalgrimaud/jhipster-burger-cypress
- the config is by default, with JWT auth
- I launch npm run e2e :

```
➜ npm run e2e  

> burger-cypress@0.0.0 e2e /home/pgrimaud/tmp/13-cypress
> npm run e2e:cypress


> burger-cypress@0.0.0 e2e:cypress /home/pgrimaud/tmp/13-cypress
> cypress run --browser chrome


============================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    5.5.0                                                                              │
  │ Browser:    Chrome 86                                                                          │
  │ Specs:      6 found (account/login-page.spec.ts, account/password-page.spec.ts, account/regist │
  │             er-page.spec.ts, account/reset-password-page.spec.ts, account/settings-page.spec.t │
  │             s, administration/administration.spec.ts)                                          │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  account/login-page.spec.ts                                                      (1 of 6)


  login modal
    ✓ greets with signin (1534ms)
    ✓ requires username (716ms)
    ✓ requires password (533ms)
    ✓ errors when password is incorrect (1256ms)
    ✓ go to login page when successfully logs in (669ms)


  5 passing (5s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      5                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     4 seconds                                                                        │
  │ Spec Ran:     account/login-page.spec.ts                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  account/password-page.spec.ts                                                   (2 of 6)


  /account/password
    ✓ requires current password (2702ms)
    ✓ requires new password (356ms)
    ✓ requires confirm new password (752ms)
    ✓ should fail to update password when using incorrect current password (1589ms)
    ✓ should be able to update password (855ms)


  5 passing (6s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      5                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     6 seconds                                                                        │
  │ Spec Ran:     account/password-page.spec.ts                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  account/register-page.spec.ts                                                   (3 of 6)


  /account/register
    ✓ should load the register page (1425ms)
    ✓ requires username (354ms)
    ✓ requires email (408ms)
    ✓ requires email in correct format (327ms)
    ✓ requires first password (405ms)
    ✓ requires password and confirm password to be same (634ms)
    ✓ requires password and confirm password have not the same value (826ms)
    ✓ register a valid user (1378ms)


  8 passing (6s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        8                                                                                │
  │ Passing:      8                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     5 seconds                                                                        │
  │ Spec Ran:     account/register-page.spec.ts                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  account/reset-password-page.spec.ts                                             (4 of 6)


  forgot your password
    ✓ requires email (2207ms)
    ✓ should be able to init reset password (338ms)


  2 passing (3s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     account/reset-password-page.spec.ts                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  account/settings-page.spec.ts                                                   (5 of 6)


  /account/settings
    ✓ should be able to change 'user' firstname settings (3152ms)
    ✓ should be able to change 'user' lastname settings (828ms)
    ✓ should be able to change 'user' email settings (528ms)
    ✓ should not be able to change 'user' settings if email already exists (4667ms)


  4 passing (9s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        4                                                                                │
  │ Passing:      4                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     9 seconds                                                                        │
  │ Spec Ran:     account/settings-page.spec.ts                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  administration/administration.spec.ts                                           (6 of 6)


  /admin
    /user-management
      ✓ should load the page (2240ms)
    /metrics
      ✓ should load the page (204ms)
    /health
      ✓ should load the page (1120ms)
    /logs
      ✓ should load the page (768ms)
    /configuration
      ✓ should load the page (177ms)


  5 passing (5s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      5                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     4 seconds                                                                        │
  │ Spec Ran:     administration/administration.spec.ts                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


============================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  account/login-page.spec.ts               00:04        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  account/password-page.spec.ts            00:06        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  account/register-page.spec.ts            00:05        8        8        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  account/reset-password-page.spec.ts      00:02        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  account/settings-page.spec.ts            00:09        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  administration/administration.spec.      00:04        5        5        -        -        - │
  │    ts                                                                                          │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:33       29       29        -        -        -  



```

**Comment by tillias** [comment]
Great, many thanks! Now it works fine. I hope it will be possible to migrate from jhipster 6 to jhipster 7 without manually copying all the crap I have now :)

**Pull request closed without merging**
