### PR TITLE
Improve client compliance with entity generation + Fix i18n failed im…

### PR DESCRIPTION
**Pull request by sahbi-ktifa**
- Add missing default build tasks
- Add anchor for entity generation compliance

### CODE REVIEW

**Comment by sahbi-ktifa** [comment]
Please @deepu105, could you review this one ?

**Comment by deepu105** [comment]
Will do it this weekend

**Comment by sahbi-ktifa** [comment]
As @hdurix and @deepu105 approved, I merged it as I need these changes for entities PR

**Comment by pascalgrimaud** [comment]
Good job @sahbi-ktifa 
I'll do my best to find time to work on Travis / Azure builds

**Pull request merged**
