### PR TITLE
replace table by message when no entities in list

### PR DESCRIPTION
**Pull request by clement26695**
Same as jhipster/generator-jhipster#9678

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [ ] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by clement26695** [comment]
Do I have to add a test to see if the elements is correctly displayed depending if itemCount is 0 or above ?

**Comment by sahbi-ktifa** [comment]
No this is fine like that

**Comment by hdurix** [comment]
@clement26695 same - could you please rebase now #393 is merged: CI tests should be green now :)

**Comment by vishal423** [comment]
@clement26695, can you check if below scenario works with your change:
- If you navigate to list page, then, it shouldn't show the `No entities found` message while the fetch operation is in progress.

**Comment by clement26695** [comment]
Done @vishal423 ! I updated the page to know if the fetch operation is in progress

**Comment by hdurix** [comment]
Thanks @clement26695!

**Pull request merged**
